import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto flex flex-col h-screen">
        <header className="text-center p-4 bg-yellow-100">
          <h1>Budimex Document Extractor</h1>
        </header>
        <main className="grow items-center content-center p-4">{children}</main>
        <footer className="text-center p-4 bg-yellow-100">footer</footer>
      </body>
    </html>
  );
}
